[tools]
python = "3.14.2"
node = "latest"
pnpm = "latest"
ripgrep = "latest"
starship = "latest"
zoxide = "0.9.8"
lazygit = "latest"
neovim = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
